PLOBJECT_LIBNAME := plobject
PLOBJECT_SHARED_LIBRARY := $(PLOBJECT_DIR)/lib$(PLOBJECT_LIBNAME).so
PLOBJECT_STATIC_LIBRARY := $(PLOBJECT_DIR)/lib$(PLOBJECT_LIBNAME).a

PLOBJECT_SOURCE_FILES := $(wildcard $(PLOBJECT_DIR)/*.c)
PLOBJECT_OBJECT_FILES := $(patsubst %.c,%.o,$(PLOBJECT_SOURCE_FILES))
PLOBJECT_HEADER_FILES := $(wildcard $(PLOBJECT_DIR)/*.h)
PLOBJECT_INCLUDE_FLAGS := -I$(VASQ_INCLUDE_DIR)

CLEAN_TARGETS += plobject_clean

PLOBJECT_DEPS_FILE := $(PLOBJECT_DIR)/deps.mk
DEPS_FILES += $(PLOBJECT_DEPS_FILE)

$(PLOBJECT_DEPS_FILE): $(PLOBJECT_SOURCE_FILES) $(PLOBJECT_HEADER_FILES) $(VASQ_HEADER_FILES)
	rm -f $@
	for file in $(PLOBJECT_SOURCE_FILES); do \
	    echo "$(PLOBJECT_DIR)/`$(CC) $(PLOBJECT_INCLUDE_FLAGS) -MM $$file`" >> $@ && \
	    echo '\t$$(CC) $$(CFLAGS) -fpic -ffunction-sections $(PLOBJECT_INCLUDE_FLAGS) -c $$< -o $$@' >> $@; \
	done
include $(PLOBJECT_DIR)/deps.mk

$(PLOBJECT_SHARED_LIBRARY): $(PLOBJECT_OBJECT_FILES)
	$(CC) -shared -o $@ $^

$(PLOBJECT_STATIC_LIBRARY): $(PLOBJECT_OBJECT_FILES)
	ar rcs $@ $^

plobject_clean:
	rm -f $(PLOBJECT_SHARED_LIBRARY) $(PLOBJECT_STATIC_LIBRARY) $(PLOBJECT_OBJECT_FILES)
