PLOBJECT_LIBNAME := plobject
PLOBJECT_SHARED_LIBRARY := $(PLOBJECT_DIR)/lib$(PLOBJECT_LIBNAME).so
PLOBJECT_STATIC_LIBRARY := $(PLOBJECT_DIR)/lib$(PLOBJECT_LIBNAME).a

PLOBJECT_OBJECT_FILES := $(patsubst %.c,%.o,$(wildcard $(PLOBJECT_DIR)/*.c))
PLOBJECT_HEADER_FILES := $(wildcard $(PLOBJECT_DIR)/*.h)

CLEAN_TARGETS += plobject_clean

$(PLOBJECT_SHARED_LIBRARY): $(PLOBJECT_OBJECT_FILES)
	$(CC) -shared -o $@ $^

$(PLOBJECT_STATIC_LIBRARY): $(PLOBJECT_OBJECT_FILES)
	ar rcs $@ $^

$(PLOBJECT_DIR)/%.o: $(PLOBJECT_DIR)/%.c $(PLOBJECT_HEADER_FILES) $(VASQ_HEADER_FILES)
	$(CC) $(CFLAGS) -fpic -ffunction-sections -I$(VASQ_INCLUDE_DIR) -c $< -o $@

plobject_clean:
	rm -f $(PLOBJECT_SHARED_LIBRARY) $(PLOBJECT_STATIC_LIBRARY) $(PLOBJECT_OBJECT_FILES)
