#ifndef __PIPELINE_ERROR_H__
#define __PIPELINE_ERROR_H__

typedef enum {
	PL_ERROR_OK=0,
	PL_ERROR_FILE_ACCESS,
	PL_ERROR_FILE_READ,
	PL_ERROR_MEMORY,
	PL_ERROR_LEX,
	PL_ERROR_GRAMMAR,
} plErrorCode;

#endif // __PIPELINE_ERROR_H__