#ifndef __PIPELINE_MARKER_H__
#define __PIPELINE_MARKER_H__

enum plMarkerValue {
	PL_MARKER_TRUE = 258,
	PL_MARKER_FALSE,
	PL_MARKER_BLANK,
	PL_MARKER_NULL,
	PL_MARKER_LSHIFT,
	PL_MARKER_RSHIFT,
	PL_MARKER_TYPE_INT,
	PL_MARKER_TYPE_FLOAT,
	PL_MARKER_TYPE_BOOL,
	PL_MARKER_TYPE_BYTES,
	PL_MARKER_TYPE_ARRAY,
	PL_MARKER_COMPARISON_EQ,
	PL_MARKER_COMPARISON_NOT_EQ,
	PL_MARKER_COMPARISON_LESS,
	PL_MARKER_COMPARISON_LESS_EQ,
	PL_MARKER_COMPARISON_GREATER,
	PL_MARKER_COMPARISON_GREATER_EQ,
	PL_MARKER_CONTEXT_STORE,
};

#endif // __PIPELINE_MARKER_H__